### ISSUE TITLE
Missing text in reset and lock/unlock window buttons

### ISSUE THREAD

**Issue by mIRCon** [msarilar/EDEngineer#426] opened 2018-07-01 12:03 UTC
![image](https://user-images.githubusercontent.com/40735411/42134231-85e92fc2-7d37-11e8-9647-c15e6bc804cb.png)

Text for reset and lock/unlock window buttons are missing since last few versions.
I have tried full wipe of EDEngineer (including roaming appdata's edengineer folder) but the result is the same. Text are missing no matter if window is locked or unlocked or resized.
Picture is attached.

**Comment by mIRCon** [comment] 2018-07-01 12:15
Ok, maybe it was a bit too hasty comment since resizing across the screen made the text finally to appear. I had to lower font size for bottom panel in order for it to appear and still it's taking a lot of space on the screen with resized fonts.
Is that intended behaviour?
![image](https://user-images.githubusercontent.com/40735411/42134298-2c9d165c-7d39-11e8-81cd-eb69ec59e567.png)

**Comment by paradisephill** [comment] 2018-07-05 16:05
I'm having the same problem on a brand new installation. Looking forward to using it.

**Comment by msarilar** [comment] 2018-07-05 20:19
I think it's because the window is not wide enough to show the path at the bottom right and that makes the entire bottom row misaligned

try to resize the window until I fix this

**Comment by mIRCon** [comment] 2018-07-05 21:08
Can be, indeed, but if we widen it to satisfy default font size that means it'll cover most of the screen and then the transparency/overlay somewhat loses it's point.
I just decreased font size for bottom part of the window (in settings) and that "fixed" it for now.
Maybe to put smaller font size as default setting in new installations as well or dynamically adjust it to the relative window size.

**Comment by paradisephill** [comment] 2018-07-05 21:17
The problem is that the "System"/"Last Status" line does not word wrap correctly and the default window size in a new installation requires it to wrap. When the window size is small enough to force the text to wrap, it along with the two buttons, drops down a line instead causing it to be unreadable.

Changing the font size worked for me too, once I figured out where the option was.

**Comment by msarilar** [comment] 2018-07-07 09:39
fixed in 1.1.3.3

**Closed by msarilar** 2018-07-07 09:39 UTC
Labels: bug, question
