### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by betatrialz** [msarilar/EDEngineer#8] opened 2016-11-05 09:36 UTC
when i click the setup link it pops up with an error for unknown material :fedcorecomposites but does not install or open, it pops up 2 of the messages back to back

**Comment by msarilar** [comment] 2016-11-05 11:38
duplicates https://github.com/msarilar/EDEngineer/issues/6

**Comment by msarilar** [comment] 2016-11-05 12:42
Fix deployed, please restart the application

**Comment by betatrialz** [comment] 2016-11-06 03:59
i dont get any erros this time, but nothing happends in game... nothing in task manager to right click on, and atarl+f10 does nothing

**Comment by msarilar** [comment] 2016-11-06 11:43
I'm going to need your Elite Dangerous log folder in a zip file:

C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous

(you can attach the archive in your next reply here)

**Comment by betatrialz** [comment] 2016-11-06 21:57
journels sent

**Comment by msarilar** [comment] 2016-11-06 22:18
emailed where? can you upload them here?

**Comment by betatrialz** [comment] 2016-11-06 22:21
i emailed when i replied from email... i tried from the site but siad rar
file not supported

**Comment by msarilar** [comment] 2016-11-06 22:25
try with a .zip file rather than a .rar

**Comment by betatrialz** [comment] 2016-11-06 22:27
just tried with win zip .zip file said not supported... even tried just postin the .txt file directly same thing

**Comment by msarilar** [comment] 2016-11-06 22:28
I can't help without logs anyway :/
Have you tried starting the app again? maybe a couple updates I pushed fixed your issue.

**Comment by betatrialz** [comment] 2016-11-06 22:29
tried after the unkown data issue... it acts like its opening... but when im lookin at my game i see nothing, i push ctrl+f10, nothing, and in task try theres nothing thre to right click on for settings or anything

**Comment by betatrialz** [comment] 2016-11-06 22:31
can i email them to you directly?

**Comment by msarilar** [comment] 2016-11-06 22:32
try here sleclodrem@throwam.com

**Comment by betatrialz** [comment] 2016-11-06 22:35
sent

**Comment by msarilar** [comment] 2016-11-06 22:47
ok so the failure is due to malformed json file outputted by the game.
this line specifically :
{ "timestamp":"2016-10-27T06:46:13Z", "event":"Interdiction", "Success":true, "IsPlayer":true, "Interdicted":Tsunami_120681, "CombatRank":8 }

in file Journal.161027020831.01.log

I'll try to handle it (by ignoring the line)

**Comment by betatrialz** [comment] 2016-11-06 22:50
ah glad it was easy to spot.. i was really bummed.. just let me know what i need to do, so why is there nothing in my task bar or anything? is it from that line as well?

**Comment by msarilar** [comment] 2016-11-06 22:59
I'll push something, you have a couple of them lines in your logs. Probably from beta ? This is definitely invalid json and probably Frontier realized it and fixed the bug. It makes the app crash as I've configured the parser to be strict.

**Comment by betatrialz** [comment] 2016-11-06 23:00
oh no i dont have beta, but glad the issue was found so can be fixed...  hopefully other people have the same issue will be able to use it

**Comment by msarilar** [comment] 2016-11-06 23:21
new version deployed
could you confirm it fixes your issue?

**Comment by betatrialz** [comment] 2016-11-07 01:05
yep that did i can see the window now... thanks soo much

**Closed** 2016-11-07 07:38 UTC
Labels: bug, Frontier Bad Logs

**Comment by betatrialz** [comment] 2016-11-07 08:41
ell i dont seem to be auto updating, i picked up for micro weave hoses and
it never updated it by iself

**Comment by msarilar** [comment] 2016-11-07 08:57
* How did you pick them up? Could you check in your game logs (the last file updated) for the line in question and paste the line here?
* If you restart the application, is the modification taken into account?

**Comment by betatrialz** [comment] 2016-11-07 09:06
im not sure i just manually added them after i relized it didnt... i used
liimpets.. i will fidn the log for you
now

**Comment by betatrialz** [comment] 2016-11-07 09:08
{ "timestamp":"2016-11-07T08:38:05Z", "event":"ReceiveText",
"From":"$cmdr_decorate:#name=King0fgames;", "From_Localised":"CMDR
King0fgames", "Message":"ejected", "Channel":"player" }
{ "timestamp":"2016-11-07T08:38:20Z", "event":"CollectCargo",
"Type":"coolinghoses", "Stolen":false }
{ "timestamp":"2016-11-07T08:38:20Z", "event":"CollectCargo",
"Type":"coolinghoses", "Stolen":false }
{ "timestamp":"2016-11-07T08:38:26Z", "event":"CollectCargo",
"Type":"coolinghoses", "Stolen":false }
{ "timestamp":"2016-11-07T08:38:28Z", "event":"CollectCargo",
"Type":"coolinghoses", "Stolen":false }
{ "timestamp":"2016-11-07T08:38:41Z", "event":"SendText",
"To":"$cmdr_decorate:#name=King0fgames;", "To_Localised":"CMDR
King0fgames", "Message":"cool thnx budd" }

**Comment by betatrialz** [comment] 2016-11-07 09:09
i also colected some data earlier... and it didnt auto update i had to
mananulay add it for *Classified Scan Databanks*

**Comment by msarilar** [comment] 2016-11-07 09:20
can't reproduce.
* If you restart the application, is the modification taken into account?
* Are your logs located in the default folder? `C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous`

**Comment by betatrialz** [comment] 2016-11-07 09:21
no thats where they are at...
ill find a uss and find something to pick up and see

**Comment by betatrialz** [comment] 2016-11-07 09:27
yes if i restart the program it does register them

**Comment by msarilar** [comment] 2016-11-07 10:50
so you're saying that if you discard something in the game, it's not repercuted in the application? if yes, I'll check that later today.

**Comment by betatrialz** [comment] 2016-11-07 11:50
if i aquire or get rid of an item, the app does not register it unless i
restart the app completely

**Comment by msarilar** [comment] 2016-11-07 12:44
I found an issue that would make the application lose synchronization with the log files if the user unlocks/locks the window ; I'm going to fix this. Are you performing these actions after having started the application?

**Comment by betatrialz** [comment] 2016-11-07 12:49
no its unlocked when i start it i do belive

**Comment by msarilar** [comment] 2016-11-07 12:57
not possible ; so you probably unlock it manually without thinking about it, which would explain why you lose sync. I'll publish the release tonight (EU time), I need my cert to sign the binary (I'm at work).

**Comment by msarilar** [comment] 2016-11-07 18:35
should be fixed after updating

please open a new issue if it still remains, let's wrap up this one
