### ISSUE TITLE
[Elite Dangerous Update] : Report Log Errors Here

### ISSUE THREAD

**Issue by ghost** [msarilar/EDEngineer#473] opened 2018-12-12 02:41 UTC
![capture](https://user-images.githubusercontent.com/45807667/49843492-70d4a400-fd8d-11e8-96d2-76bba98f2364.PNG)

**Comment by hammerman1993** [comment] 2018-12-12 04:04
I'm getting the same thing.

**Comment by msarilar** [comment] 2018-12-12 08:22
thanks for the report!

seems like an issue with the new update's logs ; does the application runs fine after this?

it would be neat for you to upload your latest logs here so that I can check stuff tonight

**Comment by naxsor** [comment] 2018-12-12 08:40
What logs do you want? show me the way

**Comment by scotty113** [comment] 2018-12-12 11:15
Its the same for me.  If I knew what to send I would :)

**Comment by amaxcz** [comment] 2018-12-12 13:15
![31783941-fe27-48aa-ad27-010fecf5fc92](https://user-images.githubusercontent.com/413568/49872108-5c89b900-fe18-11e8-9435-50c71539cf34.png)

**Comment by jonnyroz** [comment] 2018-12-12 16:43
Just thought I'd add my experience to this.

Exact same error message as above - app will never complete loading and clicking the OK button just repeats the same message.

I tried uninstalling EDEngineer, downloading a fresh copy and reinstalling, to no avail.

**Comment by LtSten** [comment] 2018-12-12 19:50
Also getting the same error as above - happens every time my limpet stock updates (i.e. both buying and firing) - haven't (yet) tried anything else that changes inventory storage.

**Comment by waterlubber** [comment] 2018-12-12 21:48
![image](https://user-images.githubusercontent.com/7517025/49900789-90bba480-fe2d-11e8-9c03-63ef3ebed7e6.png)
Same error here. It was caused by limpet cargo changes, ie when a limpet is fired and such. Attached is a journal from last night where I experienced the error several times when mining. 
[Journal.181211182604.01.log](https://github.com/msarilar/EDEngineer/files/2673668/Journal.181211182604.01.log)

**Comment by bk1984** [comment] 2018-12-13 01:11
Getting the same errors as described above. Limpets seem to be one of the causes.

**Comment by PeferG17** [comment] 2018-12-13 02:01
I have had both problems people are talking about, earlier today it gave me the error everytime I launched a limpet and I would just close it and everything was fine. But this evening I made the mistake of launching ED Engineer while I was launching limpets and it froze ED Engineer with that error in the background. Now I can't launch ED Engineer just like Burnwine. Additionally I tried dumping all my limpets and then launching ED Engineer but that didn't help, now I just have the same error but it says 0 under the count instead of the previous number.

**Comment by matt232h** [comment] 2018-12-13 06:33
Same issue here seems to be related to cargo events (i.e. "Cargo") that are created after anything changes the quantity of the cargo in you hold (i.e. "MissionCompleted", "MarketSell", "MarketBuy", "BuyDrones", "LaunchDrone").

Ok Cargo events (seems to be the intial load of the game)
===========
{ "timestamp":"2018-12-12T11:28:49Z", "event":"Cargo", "Vessel":"Ship", "Count":449, "Inventory":[ { "Name":"cmmcomposite", "Name_Localised":"CMM Composite", "Count":20, "Stolen":0 }, { "Name":"syntheticfabrics", "Name_Localised":"Synthetic Fabrics", "Count":105, "Stolen":0 }, { "Name":"semiconductors", "Count":46, "Stolen":0 }, { "Name":"polymers", "Count":14, "Stolen":0 }, { "Name":"computercomponents", "Name_Localised":"Computer Components", "Count":38, "Stolen":0 }, { "Name":"powergenerators", "Name_Localised":"Power Generators", "Count":24, "Stolen":0 }, { "Name":"superconductors", "Count":23, "Stolen":0 }, { "Name":"waterpurifiers", "Name_Localised":"Water Purifiers", "Count":32, "Stolen":0 }, { "Name":"ceramiccomposites", "Name_Localised":"Ceramic Composites", "Count":147, "Stolen":0 } ] }
{ "timestamp":"2018-12-12T13:45:38Z", "event":"Cargo", "Vessel":"Ship", "Count":61, "Inventory":[ { "Name":"drones", "Name_Localised":"Limpet", "Count":61, "Stolen":0 } ] }


Bad Cargo Events
============
{ "timestamp":"2018-12-12T11:42:49Z", "event":"Cargo", "Vessel":"Ship", "Count":442 }
{ "timestamp":"2018-12-12T12:05:11Z", "event":"Cargo", "Vessel":"Ship", "Count":380 }
{ "timestamp":"2018-12-12T11:42:55Z", "event":"Cargo", "Vessel":"Ship", "Count":435 }
etc

The new API document notes the following, could be related.....but not sure why one type of cargo event or ok when the other isn't.
https://forums.frontier.co.uk/showthread.php/452937-Journal-Docs-for-v3-3
"Summary of changes in Beta3:
<snip>
• Cargo – fix spurious extra events; add a flag to indicate vessel=Ship or Vessel=SRV
<snip>"

**Comment by Slegnor** [comment] 2018-12-13 10:42
Just to confirm, I have been getting the same error, the only cargo on my ship are limpets and the warning box pops up equal to the difference between my limpet count at login and the count at logout (I had 7, now 3, error box reappeared 4 times)
App continued to work after the error was cleared

**Comment by CmdrWode** [comment] 2018-12-13 10:50
# 2018-12-09

## Upon loading cmdr:
{ "timestamp":"2018-12-09T09:58:27Z", "event":"Cargo", "Inventory":[ { "Name":"drones", "Name_Localised":"Limpet", "Count":3, "Stolen":0 } ] }

## After buying limpets:
{ "timestamp":"2018-12-09T09:58:49Z", "event":"BuyDrones", "Type":"Drones", "Count":7, "BuyPrice":101, "TotalCost":707 }
(no cargo update event after buying action)


# 2018-12-13

## Buying and selling 10 limpets:
{ "timestamp":"2018-12-13T08:01:44Z", "event":"BuyDrones", "Type":"Drones", "Count":10, "BuyPrice":101, "TotalCost":1010 }
{ "timestamp":"2018-12-13T08:01:46Z", "event":"Cargo", "Vessel":"Ship", "Count":10 }						<-- this causes error
{ "timestamp":"2018-12-13T08:02:09Z", "event":"SellDrones", "Type":"Drones", "Count":10, "SellPrice":100, "TotalSale":1000 }
{ "timestamp":"2018-12-13T08:02:12Z", "event":"Cargo", "Vessel":"Ship", "Count":0 }						<-- this causes error

So the problem is caused by the cargo event no longer specifying what the cargo is in some circumstances:

After loading game: Inventory specified
After buying selling/selling/scooping/ejecting: Inventory not specified

This 'cargo [count only] update' event should have been given a different name as it doesn't list the cargo. I'm not sure whether this was intentional or not.

Stopping the exception is straightforward, but this 'count only' cargo event needs to be filtered out otherwise it will continually be resetting all your commodities to 0.

I'll have a look at the code.

**Comment by CmdrWode** [comment] 2018-12-13 12:11
So this fix appears to work. (The code already deals with null being returned).

I did a quick test buying Progenitor Cells, buying and selling limpets and making sure commodities did not get reset to zero.

```c#
        private JournalOperation ExtractCargoDump(JObject data)
        {
            var dump = new DumpOperation
            {
                ResetFilter = new HashSet<Kind>
                {
                    Kind.Commodity
                },
                DumpOperations = new List<MaterialOperation>()
            };

            // ED version 3.3 (December 11th 2018) made some breaking changes:
            //  - Cargo event was added after buying/selling/scooping/ejecting commodities/limpets
            //  - But unfortunately this Cargo event is different to normal Cargo event and does not contain the Inventory key (so it needs to be ignored)
            //  - Note that when cmdr is loaded/game is started, Cargo event DOES contain the Inventory field
            if (data["Inventory"] == null)
                return null;

            foreach (var jToken in data["Inventory"])
            {
                ...
            }

            return dump;
        }
```

**Comment by msarilar** [comment] 2018-12-13 12:39
yes I was thinking of something like this

if you open a PR for this, make sure the test is done before the `new DumpOperation` and do add brackets around the `if` (even if it's a single line)

**Comment by CmdrWode** [comment] 2018-12-13 14:14
Done. Submitted PR #477

**Comment by msarilar** [comment] 2018-12-13 20:48
all right everything's deployed, let me know if there are any other issues ! thanks everyone

**Comment by CmdrWode** [comment] 2018-12-13 20:59
Just installed the new version. Looks good. Will fly around a bit and give it a test.

**Comment by cmdr-escalona** [comment] 2018-12-18 03:19
Same problem here :(

**Comment by msarilar** [comment] 2018-12-18 08:47
make sure you're using the latest version 1.1.4.1 :
![image](https://user-images.githubusercontent.com/5569959/50142210-d2bf6d00-02a9-11e9-856c-2bc670d0f621.png)

if you are, you'll need to upload your journal logs here so I can have a look

**Comment by cmdr-escalona** [comment] 2018-12-18 14:32
This happens to me when I try to install the new application.


INFORMACIÓN DE VERSIÓN DE LA PLATAFORMA
	Windows 			: 10.0.17134.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3056.0 built by: NET472REL1
	clr.dll 			: 4.7.3260.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3056.0 built by: NET472REL1
	dfshim.dll 			: 10.0.17134.1 (WinBuild.160101.0800)

ORÍGENES
	Dirección URL de la implementación			: https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application

RESUMEN DEL ERROR
	Abajo se muestra un resumen de los errores; los detalles de estos errores se incluyen en el registro.
	* La activación de https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application dio como resultado una excepción. Se detectaron los siguientes mensajes de error:
		+ El ensamblado referido no está instalado en su sistema. (Excepción de HRESULT: 0x800736B3)

RESUMEN DE ERRORES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
	No se detectó ningún error de transacción.

ADVERTENCIAS
	No se generó ninguna advertencia durante esta operación.

ESTADO DE PROGRESO DE LA OPERACIÓN
	* [18/12/2018 09:29:46] : Se ha iniciado la activación de https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application.

DETALLES DEL ERROR
	Se detectaron los siguientes errores durante esta operación.
	* [18/12/2018 09:29:56] System.Runtime.InteropServices.COMException
		- El ensamblado referido no está instalado en su sistema. (Excepción de HRESULT: 0x800736B3)
		- Origen: System.Deployment
		- Seguimiento de la pila:
			en System.Deployment.Internal.Isolation.IStore.GetAssemblyInformation(UInt32 Flags, IDefinitionIdentity DefinitionIdentity, Guid& riid)
			en System.Deployment.Internal.Isolation.Store.GetAssemblyManifest(UInt32 Flags, IDefinitionIdentity DefinitionIdentity)
			en System.Deployment.Application.ComponentStore.GetAssemblyManifestFromStore(DefinitionIdentity asmId)
			en System.Deployment.Application.ComponentStore.GetAssemblyManifestWithRetry(DefinitionIdentity asmId, TimeSpan retryInterval, Int32 maxRetryCount)
			en System.Deployment.Application.ComponentStore.GetSubscriptionStateInternal(DefinitionIdentity subId)
			en System.Deployment.Application.SubscriptionStore.GetSubscriptionStateInternal(SubscriptionState subState)
			en System.Deployment.Application.SubscriptionStore.CheckAndReferenceApplication(SubscriptionState subState, DefinitionAppId appId, Int64 transactionId)
			en System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			en System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
			en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			en System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			en System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

DETALLES DE TRANSACCIÓN DEL ALMACÉN DE COMPONENTES
	No hay información disponible sobre la transacción.

**Comment by CmdrWode** [comment] 2018-12-18 18:44
My best guess from a quick google would be that your Windows ClickOnce Application has become  corrupted.

See https://stackoverflow.com/questions/20370490/system-runtime-interopservices-comexception-when-installing-github-for-windows

Not sure if the corruption pertains to EdEngineer, the GitHub installer, or something else. You could try the following:

_Option 1_
- From Windows control panel, find "Programs and Features" (or whatever it's called in Spanish on Windows 10 - "Aplicaciones y caracteristicas" I think)
- Find EdEngineer in the list of apps and uninstall it
- Reboot machine
- Try reinstall of EdEngineer

_Option 2_
- Take a backup copy of folder %LocalAppData%\Apps\2.0
- From a console with Admin rights, run the following command:

	rundll32 %windir%\system32\dfshim.dll CleanOnlineAppCache

- Reboot machine
- Try reinstall of EdEngineer

_Option 3_
- Take a backup copy of folder %LocalAppData%\Apps\2.0
- Delete contents of %LocalAppData%\Apps\2.0
- Reboot machine
- Try reinstall of EdEngineer

Options 2 and 3 use at your own risk, since I am not sure of the implications of clearing this cache on Windows - it's not something I've had to do before.

**Closed** 2019-02-06 21:48 UTC
Labels: 4.0, RefData, bug, technical
