### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by markjfisher** [msarilar/EDEngineer#315] opened 2018-03-04 10:37 UTC
After using material trader, any that I moved about have become negative, e.g.

![image](https://user-images.githubusercontent.com/1616940/36944599-fca968b4-1f97-11e8-967d-80646dbd315d.png)

**Comment by markjfisher** [comment] 2018-03-04 10:38
logging out and in fixes as it rescans

**Comment by msarilar** [comment] 2018-03-04 11:08
duplicate of #313

**Closed by msarilar** 2018-03-04 11:08 UTC
Labels: duplicate
