### ISSUE TITLE
Number of data elements added to DB is incorrect

### ISSUE THREAD

**Issue by camper2267** [msarilar/EDEngineer#37] opened 2016-11-10 20:48 UTC
I just scanned a satellite and got 2 records of Specialized Legacy Firmware. ED added 6 of them to my databank, though EDEngineer added only 3 to its DB.

**Comment by msarilar** [comment] 2016-11-10 21:01
Thanks for the report! Could you attach your log folder zipped here please? I'll have a look.

**Comment by camper2267** [comment] 2016-11-10 21:58
Here you are


![logs](https://cloud.githubusercontent.com/assets/6142818/20196012/3483cf4a-a7b2-11e6-92af-134b60e5f7e9.jpg)

I couldn't post a zip here (don't know why) so I just changed file extension from zip to jpg. sorry for that :)

**Comment by msarilar** [comment] 2016-11-10 22:03
Sorry I need your commander's log, not your netlogs ! I should have specified.

Generally it's that folder (paste it in your explorer window) : `C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous`

**Comment by camper2267** [comment] 2016-11-10 22:26
oh, sorry. here is the correct one

again it doesn't want to upload with .zip :) so it's jpg again
![elite dangerous](https://cloud.githubusercontent.com/assets/6142818/20196894/3836e39e-a7b6-11e6-96cb-be5cb6c21510.jpg)

**Comment by msarilar** [comment] 2016-11-10 22:30
it was in Shinrarta Dezhra at Founders World ?

**Comment by camper2267** [comment] 2016-11-10 22:31
yes

**Comment by msarilar** [comment] 2016-11-10 22:41
It looks good to me.

I see 8 engineer operations removing 1 Specialised Legacy Firmware each (-8 total), and 2 datascan increasing them by 3 each (which means -2 in the counter). 

You might have not inputted the correct number manually at first?

**Comment by camper2267** [comment] 2016-11-10 22:51
No, I did input numbers for all materials and data. I had 1 SLF yesterday when I configured the EDEngineer (yes, I installed it just yesterday). It had negative number. I changed it to 1. After scanning of that satellite today I saw 4 in EDEngineer and 7 in ED.

It worked good for materials. It was my first scan of data since setup that gave 2 records and I paid attention to results.

**Comment by msarilar** [comment] 2016-11-10 22:52
If you restart the application, do you still see the same results?

**Comment by msarilar** [comment] 2016-11-10 22:54
if you could upload your `manualChanges.json` file located in `C:\Users\%USERNAME%\AppData\Local\EDEngineer`, I'll have a better idea of what happened

**Comment by camper2267** [comment] 2016-11-10 23:05
Unfortunately, we can't tell now what will happen on restart as I manually changed 4 to 7 when I noticed this bug.

Anyway, here is the file you requested

[manualChanges.json.txt](https://github.com/msarilar/EDEngineer/files/584632/manualChanges.json.txt)

**Comment by msarilar** [comment] 2016-11-10 23:14
oh I see what's wrong. you're absolutely right!
I was testing with the upcoming version of EDEngineer (not yet released) and it handles that situation very well (I see [10](http://i.imgur.com/3zTf9Pn.png) in it ; which is 7 + the 3 you added to fix).

The issue is that the two logs that got you the 3 SLF are exactly the same (ED doesn't output [GUIDs](https://fr.wikipedia.org/wiki/Globally_Unique_Identifier) with logs). The application detected a duplicate in your case, and skipped the second log.

I rewrote the way logs are parsed using a much cleaner way (less CPU drain, even if it was minimal now it's almost null) and it will handle that situation.

I'll close this issue once the new version is deployed! Know that it's ready and I planned to deploy tonight. However be aware that once you update, your logs will be fixed but the +3 you added will remain ; you'll have to remove it once again.

**Comment by msarilar** [comment] 2016-11-10 23:27
Please restart the app, it will update. Let me know if you see "10" for Specialised Legacy Firmware :)

**Closed** 2016-11-11 01:44 UTC
Labels: bug

**Comment by camper2267** [comment] 2016-11-11 10:28
yes, it show 10.

thank you :)
