### ISSUE TITLE
Some grade 5 blueprints are missing!

### ISSUE THREAD

**Issue by rizal72** [msarilar/EDEngineer#15] opened 2016-11-05 15:58 UTC
Examples:
Dirty Drive Tuning, Thermal Resistant Shields, High Charge Capacity Power Distributor, etc....

**Comment by msarilar** [comment] 2016-11-05 16:21
was due to negative numbers in your material, the issue is fixed in 1.0.0.8

**Closed by msarilar** 2016-11-05 16:21 UTC
Labels: bug
