### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by CMDR-Cometborne** [msarilar/EDEngineer#203] opened 2017-04-13 22:46 UTC
When I start a new game session in E:D 2.3, ED Engineer will crash when the first journal entries are written. If I start ED Engineer once I am in game, it will run smoothly.  However, using "save&exit to main menu" and then "start" will cause another crash.

E:D 2.3, Win 10 home, ED Engineer 1.0.5.6

**Comment by msarilar** [comment] 2017-04-14 16:45
I cannot reproduce, is it systematic?

**Comment by Stevax** [comment] 2017-04-15 05:51
Same here, get loads of pop up messages when I start the app, I go through and close them all and then it seems to run although have had to manually go through and update the values a couple of times and now some have reverted to negative numbers

**Comment by CMDR-Cometborne** [comment] 2017-04-15 08:28
Yes, it happens every time I load the game.  Unfortunately, I do not get any diagnostics other than the windows "ED Engineer has stopped working" alert box.  Just upgraded to the latest release (1.0.6.0 according to the web page, 1.0.6.4 according to the internal release notes) and the problem exists there as well.

**Comment by msarilar** [comment] 2017-04-15 09:48
upload your log folder here, I'll take a look
(rename the .zip to .jpg if github doesn't want an archive)

**Comment by msarilar** [comment] 2017-04-15 09:50
might be similar to this issue https://github.com/msarilar/EDEngineer/issues/200

maybe a reinstall will help

**Comment by ComradeNapoleon** [comment] 2017-04-16 09:12
I can also confirm this.

**Comment by msarilar** [comment] 2017-04-16 09:25
found the issue! a fix has been published in 1.0.6.6

**Closed by msarilar** 2017-04-16 09:25 UTC
Labels: bug

**Comment by CMDR-Cometborne** [comment] 2017-04-16 19:43
Fix confirmed
