### ISSUE TITLE
Program crashes when acquiring power transfer bus

### ISSUE THREAD

**Issue by CrazyPotatoes** [msarilar/EDEngineer#28] opened 2016-11-08 04:45 UTC
I didn't get much of a chance to investigate the conditions beyond this particular commodity, but when I either buy one from the market (detects change) or if I try to increase the count manually, the program crashes.

I believe the log item name is called "powertransferconduits"
{ "timestamp":"2016-11-07T22:04:34Z", "event":"MarketBuy", "Type":"powertransferconduits", "Count":4, "BuyPrice":558, "TotalCost":2232 }

I had also gotten the same crash when buying CMM composites. 

The program does not seem to crash if I already have a count logged and buy additional. Appears to only crash while originally set to zero.

**Comment by CrazyPotatoes** [comment] 2016-11-08 06:21
Important condition noticed: This crash happens when the blueprint containing it is set as a favorite.

**Comment by msarilar** [comment] 2016-11-08 08:30
So there's actually two issues here:
* powertransferconduits not being mapped to power transfer bus (easy fix)
* actual crash of the application

Regarding second point, do you have more details about what you do (like Window locked/unlocked, ...). I can't reproduce this. Is it something systematic or sometimes happen, sometimes doesn't happen?

**Comment by msarilar** [comment] 2016-11-08 12:26
* The powertransferconduits is now fixed in 1.0.0.19
* The crash is most probably the same as described in #30, let's keep related discussions in that other thread

**Closed by msarilar** 2016-11-08 12:26 UTC
Labels: bug, Frontier Bad Logs
