### ISSUE TITLE
App installs, but does not start

### ISSUE THREAD

**Issue by Mattpenfold** [msarilar/EDEngineer#379] opened 2018-04-14 08:41 UTC
I am having a problem with getting the app to run. I run the program, it looks for an update, and then it just closes. I never get an icon in the notification area. 

I am using Windows 10 64 bit, build 1803 (the latest Spring creators update). I have checked the event view and I am seeing nothing there that would seem to relate to ED Engineers.

**Comment by msarilar** [comment] 2018-04-14 09:05
duplicate of #371

**Closed by msarilar** 2018-04-14 09:05 UTC
Labels: duplicate
