### ISSUE TITLE
Error messages when launching EDEngineer

### ISSUE THREAD

**Issue by nemesyssoft** [msarilar/EDEngineer#489] opened 2019-01-24 05:24 UTC
EDEngineer has been working flawlessly for me for several months. Now, about a week or so ago, when launching the app, I get a ton of error messages like this one:

![edengineer error](https://user-images.githubusercontent.com/2309889/51656183-0f981700-1f6e-11e9-95e5-f89b7fd94567.JPG)

If I click OK, another one will appear with a different count in the structure displayed there. If I click OK a few dozens times, then EDEngieer seems to be functioning normally. This is with the latest version 1.1.2.7.
I have other apps that read the logs, like EDDiscovery and VoiceAttack and none has complained about the logs.

**Comment by msarilar** [comment] 2019-01-24 08:08
This is issue caused by the game's latest update that's been fixed in 3970b9f57382ebe5e6cf1fd6bb06f5a34fb1cdd4

1.1.2.7 is not the latest version, you can see the version list here : https://github.com/msarilar/EDEngineer/releases

it's possible your computer is blocking the automatic update process in which case you might want to uninstall your current EDEngineer version and install the latest ones (your settings should be kept but I don't guarantee it)

**Closed** 2019-03-17 19:51 UTC
Labels: Misc
