### ISSUE TITLE
Crashes when switching user

### ISSUE THREAD

**Issue by Melbridge** [msarilar/EDEngineer#201] opened 2017-04-13 16:52 UTC
Windows 10
Switch to a different user, when I switch back I get a message saying EDEngineer stopped working

**Comment by msarilar** [comment] 2017-04-13 16:59
could you upload a zip of your log folder ? I can't reproduce

(rename the .zip to .jpg if github doesn't want an archive)

**Comment by Melbridge** [comment] 2017-04-13 19:53
ED Log file?

**Comment by msarilar** [comment] 2017-04-13 20:09
copy that verbatim in your explorer address bar `C:\Users\%USERNAME%\Saved Games\Frontier Developments`

**Comment by Melbridge** [comment] 2017-04-13 20:29
![journal 170413175400 01](https://cloud.githubusercontent.com/assets/26609199/25022929/bf827758-208f-11e7-8fe1-1253dfcd9aff.jpg)
Logs from before and after last crash

This has been happening on a regular basis, not just the latest version.
Just tested it by logging into another account then back whilst leaving EDEng running but it didn't crash this time!
Maybe it's something my daughter does when she's on her account.

**Comment by msarilar** [comment] 2017-04-13 20:37
all right so there's nothing wrong with you logs, the only thing left to do it to open event viewer (windows+R, "eventvwr") and in the tree view on the left go to Windows Logs, then Application. Look for errors and critical logs related to EDEngineer and let me know!

**Comment by Melbridge** [comment] 2017-04-13 20:56
![report](https://cloud.githubusercontent.com/assets/26609199/25023921/c0c3c028-2093-11e7-8d5e-d6f3c5d88351.jpg)
Zip file of windows crash report (there are 72 crash reports in the directory)

**Comment by Melbridge** [comment] 2017-04-13 20:56
Text from eventvwr log

Fault bucket 129395609869, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: EDEngineer.exe
P2: 1.0.0.0
P3: 58b2ae65
P4: WindowsBase
P5: 4.6.1638.0
P6: 589403fa
P7: d0
P8: 2c
P9: System.ComponentModel.Win32
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1120.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDEngineer.exe_4b64a3ecde53a74953cee57db14b33c4324a179_e961a1c6_718b3264

Analysis symbol: 
Rechecking for solution: 0
Report ID: 96497a8a-0ad0-404f-8508-c1aedacb4903
Report Status: 0
Hashed bucket: d1f420abde41fbf74226e8adcc80a594

**Comment by Melbridge** [comment] 2017-04-13 20:57
Faulting application name: EDEngineer.exe, version: 1.0.0.0, time stamp: 0x58b2ae65
Faulting module name: KERNELBASE.dll, version: 10.0.14393.953, time stamp: 0x58ba586d
Exception code: 0xc000041d
Fault offset: 0x000da882
Faulting process ID: 0x4068
Faulting application start time: 0x01d2b3c9e8424511
Faulting application path: C:\Users\Dean\AppData\Local\Apps\2.0\0YW5GYP8.QV1\LRO7V1P9.L2A\eden..tion_c7c2cd04d2cdd815_0001.0000_a77f92a150bc0bfb\EDEngineer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 6db885f1-f565-44d7-84f2-ff11868c9a9f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Melbridge** [comment] 2017-04-13 20:58
Fault bucket 108806433944, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: EDEngineer.exe
P2: 1.0.0.0
P3: 58b2ae65
P4: KERNELBASE.dll
P5: 10.0.14393.953
P6: 58ba586d
P7: c000041d
P8: 000da882
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3523.tmp.WERInternalMetadata.xml
\\?\C:\Users\Dean\AppData\Local\Temp\WER3F74.tmp.appcompat.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_EDEngineer.exe_c6ec8629d1ead2be13975228f919e99ed25de2f_e961a1c6_128f4119

Analysis symbol: 
Rechecking for solution: 0
Report ID: 6db885f1-f565-44d7-84f2-ff11868c9a9f
Report Status: 1
Hashed bucket: 39f689d1adbfd4362090b3f103f414e2

**Comment by msarilar** [comment] 2017-04-13 21:16
that's interesting, but a bit too cryptic for me to understand what's wrong unfortunately

if you notice any pattern for when it crashes, it's worth sharing even if it turns out to not be the case (like you initially thought it was because of commander switching)

I'm closing that one but don't hesitate to open it again if you find anything new

**Closed by msarilar** 2017-04-13 21:16 UTC
Labels: bug

**Comment by Melbridge** [comment] 2017-04-13 21:43
Well I'd love to say I could help but it means virtually nothing to me!!
I'll keep an eye on it.
BTW it's not switching commanders
It's when I've left EDEng running and locked my windows account (win+L) then my daughter logs on to her windows account and looks at 'girl stuff' on youtube etc
Then when I log back to my windows account EDEng crashes (normally, but not always)
